ps.haweya.win.obs.web/Areas/Admin/Controllers/UserController.cs
using ps.haweya.win.obs.business.Managers;
using ps.haweya.win.obs.viewModels;
using ps.haweya.win.obs.security;
using ps.haweya.win.obs.web.App_Start;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ps.haweya.win.obs.business;

namespace ps.haweya.win.obs.web.Areas.Admin.Controllers
{

    [OBSAuthorize(Roles = "Admin")]
    public class UserController : AdminBaseController
    {
        // GET: Admin/User
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Buyers()
        {
            return View();
        }
        public ActionResult Sellers()
        {
            return View();
        }
        public JsonResult AjaxDT(string role)
        {
            var query = Request.QueryString["query[query]"] ?? "";

            var sortBy = Request.QueryString["sort[field]"];
            var sortMethod = Request.QueryString["sort[sort]"];

            var page = int.Parse(string.IsNullOrEmpty(Request.QueryString["pagination[page]"]) ? "1" : Request.QueryString["pagination[page]"]);
            var pages = int.Parse(string.IsNullOrEmpty(Request.QueryString["pagination[pages]"]) ? "1" : Request.QueryString["pagination[pages]"]);
            var perpage = int.Parse(string.IsNullOrEmpty(Request.QueryString["pagination[perpage]"]) ? "10" : Request.QueryString["pagination[perpage]"]);

            var CountryList = new CountryManager().Get();

            var items = new AspNetUsersManager().GetWithInclouds("", page, perpage, sortBy, sortMethod, query,role);
            var totalItemsCount = new AspNetUsersManager().Count(query,role);


            var result =
               new
               {
                   meta = new
                   {
                       page,
                       pages = Math.Ceiling(totalItemsCount / double.Parse(perpage + "")),
                       perpage,
                       total = totalItemsCount,
                   },
                   data = items.Select(x => new
                   {
                       x.Id,
                       Email = x.Email,
                       UserName = x.UserName,
                       EmailConfirmed = x.EmailConfirmed,
                       FullName = x.FullName,
                       PhoneNumber = x.PhoneNumber,
                       ProfilePhoto = x.ProfilePhoto,
                       CountryId = x.CountryId,
                       x.LockoutEnabled,
                       x.InsertDate,
                       Default_Role = x.AspNetUserClaims.SingleOrDefault(c => c.ClaimType == "DEFAULT_ROLE") != null ? x.AspNetUserClaims.SingleOrDefault(c => c.ClaimType == "DEFAULT_ROLE").ClaimValue.ToLower() : "",
                       TotalOrders = x.BuyerOrders.Count() > 0 ? x.BuyerOrders.Select(a => a.ID).Count() + "" : "",
                       Country = CountryList.Where(t => t.id == int.Parse(x.CountryId ?? "0")).FirstOrDefault()
                   }).ToList()


               };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index");
            var usr = new AspNetUsersManager().GetByUserId(id);
            if(usr==null)
                return RedirectToAction("Index");
            return View(usr);
        }
        public ActionResult NestedRols(string UserID)
        {
            var model = new AspNetUsersManager().GetByUserId(UserID);

            ViewBag.Countryimg = CacheManager.Countries.Where(x => x.id == Convert.ToInt32(model.CountryId ?? "0")).FirstOrDefault();

            var links = new UserLinkManager().GetByUserId(UserID).Select(x => x.LinkId);
            var UserLinks = CacheManager.Links.Where(x => links.Contains(x.Id));

            ViewBag.UserLinks = UserLinks.ToList();
            ViewBag.Links = CacheManager.Links.Except(UserLinks).ToList();

            return View(model);
            // return View("testroles");
        }

        public PartialViewResult UserLinks(string UserId)
        {
            var UserLinks = new UserLinkManager().GetByUserId(UserId).Select(x => x.LinkId);
            var defaultRole = (User.Identity as ClaimsIdentity).Claims.Single(t => t.Type.Equals("DEFAULT_ROLE"));
            var links = CacheManager.Links
                                    .Where(t => t.Area.Equals(defaultRole.Value))
                                    .Select(t=> {   t.IsSelected = UserLinks.Contains(t.Id);
                                                    return t;
                                    });

            return PartialView("_userlinks", links);
        }

        public ActionResult AddNewUser()
        {
            ViewBag.Roles = new SelectList(new AspNetRolesManager().Get().Select(x => new { x.Id, x.Name }), "Name", "Name");
            return View();
        }


        #region POST

        public JsonResult UpdateStatus(AspNetUserViewModel user)
        {
            var identityResult = new SecurityManager().UserManager.SetLockoutEnabled(user.Id, user.LockoutEnabled);
            if (user.LockoutEnabled)
            {
                AspNetUserViewModel aspnetuser = new AspNetUsersManager().GetById(user.Id);
                AspNetRoleViewModel role = new AspNetRolesManager().Get().Where(x => x.Name.ToLower().Contains("seller")).FirstOrDefault();

                if (aspnetuser.AspNetRoles.Where(x => x.Name.ToLower().Equals("seller")).Count() > 0)
                {
                    var vdetails = aspnetuser.OBSVendorDetails.FirstOrDefault();

                    if (vdetails != null)
                    {
                        if (string.IsNullOrEmpty(vdetails.VendorCode))
                        {

                            OBSVendorDetailManager vmanager = new OBSVendorDetailManager();
                            string Vcode = GetVCode();


                            vdetails.VendorCode = Vcode;
                            vmanager.Update(vdetails);
                            new MailManager().SendMessage(aspnetuser.Email, "Vendor ID ", "https://win.com.sa/Content/FrontEnd/images/logo.png", "https://win.com.sa/", "#", "we want notify you your VendorID is : " + Vcode + " . ", "Warehouse Integration Company", aspnetuser.FullName, Vcode);
                        }
                    }
                    else
                    {
                        OBSVendorDetailManager vmanager = new OBSVendorDetailManager();

                        string Vcode = GetVCode();
                        vdetails = new OBSVendorDetailViewModel();
                        vdetails.VendorCode = Vcode;
                        vdetails.UserId = aspnetuser.Id;
                        vdetails.AddedOn = DateTime.Now;

                        vmanager.Add(vdetails);
                        new MailManager().SendMessage(aspnetuser.Email, "Vendor ID", "https://win.com.sa/Content/FrontEnd/images/logo.png", "https://win.com.sa/", "#", "we want notify you your VendorID is : " + Vcode + " . ", "Warehouse Integration Company", aspnetuser.FullName, Vcode);
                    }


                }
            }

            return Json(new
            {
                Status = 200,
                Data = identityResult.Succeeded
            });
        }
        

        [HttpPost]
        public ActionResult AddNewUser(RegisterViewModel model, string Type)
        {
            ViewBag.Roles = new SelectList(new AspNetRolesManager().Get().Select(x => new { x.Id, x.Name }), "Name", "Name", Type);

            if (Type.Equals(""))
            {
                TempData["msg"] = "<div class='alert alert-danger alert-dismissible fade show' role='alert'><strong> Please select user role</strong>   <button type ='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>";
                return View(model);
            }

            model.Agreepolicies = true;
            if (ModelState.IsValid)
            {
                SecurityManager securityManager = new SecurityManager();
                string result = securityManager.CreateUser(model, Type);


                Guid guid = Guid.Empty;
                Guid.TryParse(result, out guid);


                if (guid != Guid.Empty)
                {
                    TempData["msg"] = "<div class='alert alert-success alert-dismissible fade show' role='alert'><strong> User Data Saved Successfully! </strong> All Data  Saved   <button type ='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>";
                    securityManager.VerifyUser(guid.ToString());
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("ERROR", result);
            }

            return View(model);
        }

        [HttpPost]
        public JsonResult AssignUserLinks(string userid, string ids)
        {

            string[] linkids = ids.Split(',');

            UserLinkManager umanager = new UserLinkManager();
            
                umanager.DeleteByUserID(userid);

                var list = new List<UserLinkViewModel>();

                foreach (string id in linkids)
                {
                    list.Add(new UserLinkViewModel()
                    {
                        LinkId = Convert.ToInt32(id),
                        UserId = userid,
                        CreatedBy = User.Identity.GetUserId(),
                        CreatedAt = DateTime.Now
                    });
                }

                umanager.AddLinkRangeToUser(list);

                // check if the user does not have secondary role
                var link = new LinkManager().GetById(int.Parse(linkids[0]));

ps.haweya.win.obs.web/Areas/Seller/Controllers/HomeController.cs
using Microsoft.AspNet.Identity;
using ps.haweya.win.obs.business;
using ps.haweya.win.obs.business.Managers;
using ps.haweya.win.obs.web.App_Start;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ps.haweya.win.obs.web.Areas.Seller.Controllers
{

    public class HomeController : SellerBaseController
    {
        // GET: Seller/Home
        public ActionResult Index()
        {

            string name = new AspNetUsersManager().GetByUserId(User.Identity.GetUserId()).Email;
            ViewBag.OrdersCount = new BuyerOrderManager().GetCountstoSeller(name);
            ViewBag.ProcusctsCount = new ProductInformationManager().GetCountstoAdmin(name);
            ViewBag.ProductBids = new ProductInformationManager().GetBidsProductWithseller("Auctionable",name);
            ViewBag.DirectPurchased = new ProductInformationManager().GetBidsProductWithseller("Non-Auctionable", name);
            return View("View");
        }


        public ActionResult MyAccount()
        {
            var model = new AspNetUsersManager().GetByEmail(User.Identity.Name);

            ////model.Country = CacheManager.Countries.SingleOrDefault(t => t.id.ToString() == model.CountryId);
            ////model.State = CacheManager.States.SingleOrDefault(t => t.id.ToString() == model.StateId);
            ////model.City = CacheManager.Cities.SingleOrDefault(t => t.id.ToString() == model.CityId);

            return View(model);
        }

        public JsonResult GetBidsTabel(string q = "")
        {
            string name = new AspNetUsersManager().GetByUserId(User.Identity.GetUserId()).Email;

            var list = new OBSBidDetailsManager().GetWithGroupingProductsToSeller(name,"ProductInformation", 1, 10, "bidid", "desc", q).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPRoductCountByCountry()
        {
            string name = new AspNetUsersManager().GetByUserId(User.Identity.GetUserId()).Email;

            var list = new ProductDetailsManager().GetWithGroupingProductsByCountryToSeller(name).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPRoductCountByCategory()
        {
            string name = new AspNetUsersManager().GetByUserId(User.Identity.GetUserId()).Email;
            var list = new ProductInformationManager().GetWithGroupingProductsByCategory(name).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetBidsCountByProduct()
        {
            string name = new AspNetUsersManager().GetByUserId(User.Identity.GetUserId()).Email;
            var list = new ProductInformationManager().GetWithbidcounttocahrt(name).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetBuyerssCountByCountry()
        {
            string name = new AspNetUsersManager().GetByUserId(User.Identity.GetUserId()).Email;
            var list = new AspNetUsersManager().GetBuyersGroupingByCountry(name).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult MyAccount(AspNetUserViewModel user)
        {
            new AspNetUsersManager().Update(user);
            return RedirectToAction("MyAccount");
        }
    }
}

ps.haweya.win.obs.web/Areas/Seller/Controllers/MyPreferencesController.cs
using Microsoft.AspNet.Identity;
using ps.haweya.win.obs.business;
using ps.haweya.win.obs.business.Managers;
using ps.haweya.win.obs.security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ps.haweya.win.obs.web.Areas.Seller.Controllers
{
    public class MyPreferencesController : SellerBaseController
    {
        int buyerReportId = 2;
        // GET: Seller/MyPreferences
        public ActionResult Index()
        {
            string aspnetid = User.Identity.GetUserId();

            ApplicationUser u = new SecurityManager().UserManager.FindById(aspnetid);

            BuyerViewModel b = new BuyerViewModel() { Email = u.Email, Name = u.FullName, Country = Convert.ToInt32(u.CountryId), State = Convert.ToInt32(u.StateId), City = Convert.ToInt32(u.CityId), POBox = u.POBox, ASPNetUserID = User.Identity.GetUserId(), ID = "0", Mobile = u.PhoneNumber };

            ViewBag.CUser = new AspNetUsersManager().GetByUserWithIncludes(User.Identity.GetUserId());
            ViewBag.Countries = CacheManager.Countries;
            ViewBag.Categories = new CategoryManager().Get();
            ViewBag.Manufacturers = new ManufacturerDetailsManager().Get();

            return View(b);
        }
        [HttpPost]
        public ActionResult Index(AspNetUserViewModel model)
        {
            try
            {
                var aspNetUsersManager = new AspNetUsersManager();
                var reportId = new UserReportsManager().AddOrUpdate(User.Identity.GetUserId(), buyerReportId, model.Frequency);
                new UserPreferedCategoryManager().AddRange(model.CategoriesPreferences, User.Identity.GetUserId());
                new UserPreferedManufacturerManager().AddRange(model.ManufacturersPreferences, User.Identity.GetUserId());
                new UserPreferedCountryManager().AddRange(model.CountryPreferences, User.Identity.GetUserId());

                TempData["msg"] = "s: Data Updated Successfully";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["msg"] = "e: Please Check Data You Entered";
                return RedirectToAction("Index");
            }
        }
    }
}

ps.haweya.win.obs.web/Areas/Seller/Controllers/PrintInvoiceController.cs
using Microsoft.AspNet.Identity;
using ps.haweya.win.obs.business;
using ps.haweya.win.obs.business.Managers;
using ps.haweya.win.obs.viewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ps.haweya.win.obs.web.Areas.Seller.Controllers
{
    public class PrintInvoiceController : Controller
    {
        // GET: Admin/PrintInvoice
        public ActionResult DownloadOrderInvoice(int? id, string selleremail)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BuyerOrderViewModel buyerOrder = new BuyerOrderManager().GetByid(Convert.ToInt32(id));
            ViewBag.SellerID = new AspNetUsersManager().GetByEmail(selleremail).Sellers[0].ID;
            if (buyerOrder == null)
            {
                return HttpNotFound();
            }
            ViewBag.Bank = new BankAccountsManager().Get().FirstOrDefault();
            return View(buyerOrder);
            // return new PdfResult(buyerOrder, "DownloadOrderInvoice");
        }

        public ActionResult GenerateInvoicePDF(int id, string selleremail)
        {
            return new Rotativa.ActionAsPdf("DownloadOrderInvoice", new {  id = id, selleremail = selleremail });
            //return new PdfResult( "Index");
        }
    }
}

ps.haweya.win.obs.web/Areas/Admin/Views/User/AddNewUser.cshtml
@model RegisterViewModel
@{
    ViewBag.Title = "AddNewUser";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section    Styles{

}

<!-- begin:: Subheader -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container  kt-container--fluid ">
        <div class="kt-subheader__main">

            <h3 class="kt-subheader__title"><i class="fas fa-User"></i>&nbsp;System Users</h3>

            <span class="kt-subheader__separator kt-subheader__separator--v"></span>





            <h3 class="kt-subheader__title kt-text-light">
                <a href="#" class="btn btn-label-warning btn-bold btn-sm btn-icon-h kt-margin-l-10">
                    Add New
                </a>
            </h3>
        </div>
        <div class="kt-subheader__toolbar">

        </div>
    </div>
</div>

<!-- end:: Subheader -->
<!-- begin:: Content -->
<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">


    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12" style="display:flex">
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            User Details
                        </h3>
                    </div>

                    <div class="kt-portlet__head-toolbar">
                        <div class="kt-portlet__head-actions">


                            @*<a href="#" id="resendEmail" data-orderid="$orderId" class="btn btn-label-brand btn-bold"><i class="fas fa-mail-bulk"></i>&nbsp;Resend Email</a>


                                <a href="#" id="updateCustomerEmail" class="btn btn-label-brand btn-bold edit-btn"><i class="la la-edit"></i>&nbsp;Update Email</a>
                                <a href="#" id="editOrderInformation" class="btn btn-label-brand btn-bold edit-btn kt-hidden"><i class="la la-edit"></i>&nbsp;Edit</a>
                                <a href="#" id="saveOrderInformation" class="btn btn-label-success btn-bold update-btn kt-hidden btn-success ladda-button" data-style="expand-left"><i class="la la-save"></i>&nbsp;Update</a>
                                <a href="#" id="cancelOrderInformation" class="btn btn-label-danger btn-bold cancel-btn kt-hidden"><i class="la la-times"></i>&nbsp;Cancel</a>*@
                        </div>
                    </div>

                </div>
                <div class="kt-portlet__body">

                    <form class="kt-form" action="" method="POST" id="order-form">

                        <div class="row">

                            @using (Html.BeginForm("AddNewUser", "User", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                            {
                                @Html.AntiForgeryToken()
                                <div class="col-md-12">

                                    @Html.Raw(TempData["msg"])
                                    @Html.ValidationSummary("", new { @class = "text-danger" })
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Frequency</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-user"></i></span></div>
                                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Your name" })

                                        </div>



                                    </div>

                                    <div class="form-group">
                                        <label>Email</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend"><span class="input-group-text"> <i class="fa fa-envelope-open"></i></span></div>

                                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Enter your email" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label>Password</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend"><span class="input-group-text"> <i class="fa fa-lock-open"></i></span></div>

                                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Enter your pasword" })

                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label>Confirm Password</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend"><span class="input-group-text"> <i class="fa fa-lock-open"></i></span></div>

                                            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", placeholder = "Re-enter your pasword" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label>POBox</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend"><span class="input-group-text"> <i class="fa fa-id-card"></i></span></div>


                                            @Html.TextBoxFor(m => m.POBox, new { @class = "form-control", placeholder = "P.O. Box" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label>Mobile</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend"><span class="input-group-text"> <i class="fa fa-phone"></i></span></div>

                                            @Html.TextBoxFor(m => m.Mobile, new { @class = "form-control", placeholder = "Mobile" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                         
                                    <div class="form-group">
                                        <label>Counrty</label>
                                        @Html.TextBoxFor(m => m.Counrty, new { @class = "form-control selectpicker", autocomplete = "off", id = "Country" })
                                    </div>

                                    <div class="form-group">
                                        <label>State</label>
                                        @Html.TextBoxFor(m => m.State, new { @class = "form-control selectpicker", autocomplete = "off", id = "State" })
                                    </div>

                                    <div class="form-group">
                                        <label>City</label>
                                        @Html.TextBoxFor(m => m.City, new { @class = "form-control selectpicker", autocomplete = "off", id = "City" })
                                    </div>

                                    <div class="form-group">
                                        <label>Default Role</label>
                                        @Html.DropDownList("Type", ViewBag.Roles as SelectList, "Select", new { @class = "form-control", required = "required" });
                                    </div>
                                </div>

                                <input type="hidden" value="true" name="Agreepolicies" />
                                <div class="col-md-12">
                                    <div class="form-action text-center">


                                        <button type="submit" class="btn btn-primary rounded ">
                                            Register
                                        </button>
                                    </div>
                                </div>
                            }
                        </div>



                    </form>

                </div>
            </div>
        </div>

    </div>
</div>


@section Scripts {
    <script src="/content/js/pages/crud/forms/validation/form-controls.js" type="text/javascript"></script>
    <script src="~/content/js/CountrySelect/CountryStateAndCityScripts.js"></script>
    <script>
        $(document).ready(function () {
             $("#" + CityName).select2({
                        data: City,
                        placeholder: "Select City",
                        width: "100%",
                    });

            var Country =@(Model!=null?(Model.Counrty!=null?Model.Counrty+"":""):"")+"";
            var state =@(Model!=null?(Model.State!=null?Model.State+"":""):"")+"";
            var city=@(Model!=null?(Model.City!=null?Model.City+"":""):"")+"";
        function getCityname(id) {
            $.ajax({

                url: '@Url.Content("~/Content/js/JsonData/cities.json")',
                dataType: 'json',
                type: 'GET',
                success: function (data) {
                    $.each(data, function (i, item) {
                        if (item.id == id) {

                                $("#Country").val(Country);
              $("#Country").change();
                            $("#State").val(state);
                            $("#State").change();
                        }
                    });
                },
                failure: function (response) {
                    $('#result').html(response);
                }
            });
        };
            getCityname(city);
              $("#City").val(city);

        })



    </script>
}

ps.haweya.win.obs.web/Areas/Admin/Views/User/_userlinks - Copy.cshtml
@model IEnumerable<LinkViewModel>

@{
    var index = 2;
}
<div class="dd">
    <ol class="dd-list">
        @foreach (var area in Model.GroupBy(x => x.AreaDisplayName))
        {
            <li class="dd-item first-level" data-id="1">
                
                <div class="dd-handle">
                    <label class="kt-checkbox kt-checkbox--tick kt-checkbox--brand">
                        <input type="checkbox" class="dd-item-checkbox-item" />
                        <span style="top:-4px"></span>
                    </label>
                    @(area.Key != "" ? area.Key : "Default")
                </div>
                
                @foreach (var controler in Model.Where(x => x.AreaDisplayName.Equals(area.Key)).GroupBy(x => x.ControllerDisplayName))
                {
                    <ol class="dd-list">
                        <li class="dd-item" data-id="@(index++)">
                            <div class="dd-handle">
                                <label class="kt-checkbox kt-checkbox--tick kt-checkbox--brand">
                                    <input type="checkbox" class="dd-item-checkbox-item" />
                                    <span style="top:-4px"></span>
                                </label>
                                @(controler.Key != "" ? controler.Key : "Default")
                            </div>
                            <ol class="dd-list">
                                @foreach (var Action in Model.Where(x => x.ControllerDisplayName.Equals(controler.Key) && x.AreaDisplayName.Equals(area.Key)))
                                {
                                    <li class="dd-item " data-id="@(index++)">
                                        <div class="dd-handle">
                                            <label class="kt-checkbox kt-checkbox--tick kt-checkbox--brand">
                                                <input value="@Action.Id" type="checkbox" @(Action.IsSelected ? "checked='checked'" : "")  class="dd-item-checkbox-item dd-item-checkbox-item-action" />
                                                <span style="top:-4px"></span>
                                            </label>
                                            @(Action.ActionDisplayName)
                                        </div>
                                    </li>
                                }
                            </ol>
                        </li>

                    </ol>
                }

            </li>
        }
    </ol>
</div>